version: '3.5'
services:
  mongodb:
    image: mongo:4.2
    restart: always
    container_name: what-to-watch_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
    volumes:
      - what-to-watch_data:/data/db

  mongodb-express:
    image: mongo-express:latest
    restart: always
    container_name: what-to-watch_mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb:27017/

volumes: 
  what-to-watch_data: